#!/usr/bin/env Rscript
# libcurl-ONLY parse probe (RURL-ttrcfneq).
#
# Sibling of parse-dump.R, and there are deliberately TWO scripts:
#
#   parse-dump.R  -- the FULL rurl stack (safe_parse_urls(), three
#                    url_standard settings, 18 output columns). Measures what
#                    users see. Needs rurl + stringi/ICU + pslr + punycoder,
#                    which is expensive-to-impossible to build on old distros.
#   curl-probe.R  -- THIS file. Calls libcurl and nothing else, so it runs on
#                    any R >= 3.6 with only the `curl` package. It is what the
#                    Docker matrix runs, because it isolates the ONE variable
#                    under study: libcurl's own URL parse behavior.
#
# The call is byte-identical to the one rurl makes in
# R/parse-phases.R (.parse_with_curl):
#
#     curl::curl_parse_url(input, decode = FALSE, params = FALSE)
#
# Do not "improve" those arguments: the probe is only evidence about rurl if it
# asks libcurl exactly what rurl asks it.
#
#   Rscript tools/determinism/curl-probe.R
#
# Inputs:  tools/determinism/corpus.csv (generated by corpus.R)
# Outputs: tools/determinism/out/curl-<LABEL>.csv
#          tools/determinism/out/curlenv-<LABEL>.csv
# LABEL comes from $RURL_DETERMINISM_LABEL, else <sysname>-libcurl<version>.
#
# ZERO dependencies beyond base R + the `curl` package. No rurl, no stringi,
# no jsonlite, no devtools -- so a container needs only this file plus
# corpus.csv.
#
# ENCODING CONTRACT (identical to parse-dump.R). Every value column is a JSON
# string literal: quoted, ASCII-only, non-ASCII as \uXXXX. The bare token
# `null` (unquoted) means R NA, distinguishable from the string "NA" and from
# "". Files are LF-terminated and pure ASCII by construction.
# ----------------------------------------------------------------------------

if (!requireNamespace("curl", quietly = TRUE)) {
  stop("the curl package is required.")
}

# ---- JSON escape (base R) --------------------------------------------------
# Deliberately duplicated from corpus.R / parse-dump.R so this script is
# copy-one-file runnable inside a container. The self-test below round-trips
# every corpus row through THIS copy, which also proves the copies agree.

json_escape_one <- function(s) {
  if (is.na(s)) return("null")
  cps <- utf8ToInt(enc2utf8(s))
  if (length(cps) == 1L && is.na(cps)) {
    stop("value is not valid UTF-8; cannot escape")
  }
  if (length(cps) == 0L) return("\"\"")
  out <- character(length(cps))
  for (i in seq_along(cps)) {
    cp <- cps[i]
    out[i] <- if (cp == 34L) {
      "\\\""
    } else if (cp == 92L) {
      "\\\\"
    } else if (cp == 8L) {
      "\\b"
    } else if (cp == 9L) {
      "\\t"
    } else if (cp == 10L) {
      "\\n"
    } else if (cp == 12L) {
      "\\f"
    } else if (cp == 13L) {
      "\\r"
    } else if (cp >= 32L && cp <= 126L) {
      intToUtf8(cp)
    } else if (cp <= 0xFFFFL) {
      sprintf("\\u%04x", cp)
    } else {
      u <- cp - 0x10000L
      sprintf("\\u%04x\\u%04x",
              0xD800L + u %/% 0x400L, 0xDC00L + u %% 0x400L)
    }
  }
  paste0("\"", paste(out, collapse = ""), "\"")
}

json_escape <- function(x) {
  vapply(x, json_escape_one, character(1), USE.NAMES = FALSE)
}

json_unescape_one <- function(s) {
  if (is.na(s) || identical(s, "null")) return(NA_character_)
  n <- nchar(s)
  if (n < 2L || substr(s, 1L, 1L) != "\"" || substr(s, n, n) != "\"") {
    stop("not a JSON string literal: ", s)
  }
  ch <- strsplit(substr(s, 2L, n - 1L), "", fixed = TRUE)[[1]]
  cps <- integer(0)
  i <- 1L
  m <- length(ch)
  while (i <= m) {
    if (ch[i] != "\\") {
      cps <- c(cps, utf8ToInt(ch[i]))
      i <- i + 1L
      next
    }
    e <- ch[i + 1L]
    if (e == "u") {
      hi <- strtoi(paste(ch[(i + 2L):(i + 5L)], collapse = ""), 16L)
      i <- i + 6L
      if (hi >= 0xD800L && hi <= 0xDBFFL && i + 5L <= m &&
            identical(ch[i], "\\") && identical(ch[i + 1L], "u")) {
        lo <- strtoi(paste(ch[(i + 2L):(i + 5L)], collapse = ""), 16L)
        i <- i + 6L
        hi <- 0x10000L + (hi - 0xD800L) * 0x400L + (lo - 0xDC00L)
      }
      cps <- c(cps, hi)
    } else {
      simple <- c("\"" = 34L, "\\" = 92L, "/" = 47L, "b" = 8L,
                  "f" = 12L, "n" = 10L, "r" = 13L, "t" = 9L)[e]
      if (is.na(simple)) stop("bad JSON escape: \\", e)
      cps <- c(cps, unname(simple))
      i <- i + 2L
    }
  }
  if (length(cps) == 0L) return("")
  intToUtf8(cps)
}

json_unescape <- function(x) {
  vapply(x, json_unescape_one, character(1), USE.NAMES = FALSE)
}

# ---- locate the corpus -----------------------------------------------------

find_file <- function(rel) {
  cand <- c(rel, file.path("tools", "determinism", basename(rel)),
            basename(rel))
  hit <- cand[file.exists(cand)][1]
  if (is.na(hit)) stop("cannot locate ", rel, " (run from the repo root).")
  hit
}

corpus_path <- find_file(file.path("tools", "determinism", "corpus.csv"))
corpus <- utils::read.csv(corpus_path, colClasses = "character",
                          fileEncoding = "UTF-8", stringsAsFactors = FALSE)
inputs <- json_unescape(corpus$input_json)

# ---- round-trip self-test (must run BEFORE any parsing) --------------------
# A silently lossy transport would poison every downstream diff, so fail loud.

selftest <- function() {
  probes <- c(
    inputs,
    "a\r\nb",                       # literal CRLF
    intToUtf8(c(0x01, 0x1F, 0x7F)), # NUL-free C0 controls + DEL
    intToUtf8(0x1F600),             # astral plane
    intToUtf8(0xFFFF),              # non-character
    "", " ", "NA", "null", "\"quoted\"", "back\\slash", "sl/ash"
  )
  esc <- json_escape(probes)
  if (any(grepl("[^\x20-\x7e]", esc))) {
    stop("self-test FAILED: escaped output is not ASCII-only")
  }
  back <- json_unescape(esc)
  if (!identical(back, probes)) {
    bad <- which(back != probes)
    stop("self-test FAILED: JSON round-trip lossy at ", length(bad),
         " probe(s), first index ", bad[1])
  }
  if (!is.na(json_unescape_one("null")) ||
        !identical(json_unescape_one("\"NA\""), "NA") ||
        !identical(json_unescape_one("\"\""), "")) {
    stop("self-test FAILED: NA / \"NA\" / \"\" are not distinguishable")
  }
  invisible(TRUE)
}
selftest()
cat("self-test: JSON round-trip OK over", length(inputs), "corpus rows\n")

# ---- probe -----------------------------------------------------------------

# The 9 fields curl_parse_url() returns for a URL-only parse, in curl's own
# order. Fields an older curl package omits stay NA (the `null` sentinel).
CURL_COLS <- c("url", "scheme", "user", "password", "host", "port",
               "path", "query", "fragment")

# Conditions are DATA, never aborts: a container that dies mid-corpus yields no
# evidence. curl_parse_url() is scalar-only, so this is a plain per-row loop --
# the same shape rurl's engine uses.
# Some libcurl builds hand back a field that is NOT valid UTF-8 (observed on
# libcurl 8.14.1 / curl pkg 6.2.1). That is a FINDING, not a harness bug, so it
# must not abort the run and must not be silently normalized away: render the
# raw bytes as an ASCII sentinel that no legitimate parse result can collide
# with, and flag it in curl_status.
NON_UTF8_TAG <- "<non-utf8-bytes:"

as_escapable <- function(v) {
  if (is.na(v) || validUTF8(v)) return(v)
  paste0(NON_UTF8_TAG,
         paste(sprintf("%02x", as.integer(charToRaw(v))), collapse = ""), ">")
}

probe_one <- function(x) {
  acc <- new.env(parent = emptyenv())
  acc$msgs <- character(0)
  acc$kind <- "ok"
  note <- function(kind, cnd) {
    acc$kind <- if (identical(kind, "error")) "error" else {
      if (identical(acc$kind, "error")) "error" else kind
    }
    acc$msgs <- c(acc$msgs, conditionMessage(cnd))
  }
  res <- withCallingHandlers(
    tryCatch(
      curl::curl_parse_url(x, decode = FALSE, params = FALSE),
      error = function(e) {
        note("error", e)
        NULL
      }
    ),
    warning = function(w) {
      note("warning", w)
      invokeRestart("muffleWarning")
    }
  )
  vals <- vapply(CURL_COLS, function(k) {
    if (is.null(res)) return(NA_character_)
    v <- res[[k]]
    if (is.null(v) || length(v) == 0L) return(NA_character_)
    as.character(v[[1]])
  }, character(1), USE.NAMES = FALSE)
  bad <- !is.na(vals) & !vapply(vals, validUTF8, logical(1), USE.NAMES = FALSE)
  if (any(bad)) {
    acc$msgs <- c(acc$msgs,
                  paste0("non-utf8 field(s): ",
                         paste(CURL_COLS[bad], collapse = ",")))
    if (identical(acc$kind, "ok")) acc$kind <- "warning"
    vals <- vapply(vals, as_escapable, character(1), USE.NAMES = FALSE)
  }
  status <- if (length(acc$msgs) == 0L) {
    "ok"
  } else {
    paste0(acc$kind, ": ", paste(acc$msgs, collapse = " | "))
  }
  c(status, vals)
}

t0 <- Sys.time()
raw <- vapply(inputs, probe_one, character(length(CURL_COLS) + 1L),
              USE.NAMES = FALSE)
cat(sprintf("probed %d rows in %.1fs\n", length(inputs),
            as.numeric(difftime(Sys.time(), t0, units = "secs"))))

dump <- data.frame(
  id = corpus$id,
  construct = corpus$construct,
  input_json = corpus$input_json,
  curl_status = json_escape(raw[1L, ]),
  stringsAsFactors = FALSE
)
for (i in seq_along(CURL_COLS)) {
  dump[[CURL_COLS[i]]] <- json_escape(raw[i + 1L, ])
}

# ---- environment fingerprint -----------------------------------------------

cv <- tryCatch(curl::curl_version(), error = function(e) list())
si <- Sys.info()
flat <- function(x) {
  if (length(x) == 0L || all(is.na(x))) return(NA_character_)
  paste(as.character(x), collapse = ";")
}

env_keys <- c(
  "label", "probe", "libcurl_version", "libcurl_ssl_version",
  "libcurl_ssl_backend", "libcurl_protocols", "libcurl_libidn",
  "libcurl_libssh", "libcurl_libz", "r_version", "r_platform",
  "sysname", "release", "version", "machine", "locale", "encoding",
  "curl_version_pkg", "run_utc"
)

label_raw <- Sys.getenv("RURL_DETERMINISM_LABEL", "")
if (!nzchar(label_raw)) {
  label_raw <- paste0(flat(si[["sysname"]]), "-libcurl", flat(cv$version))
}
label <- gsub("[^A-Za-z0-9._-]", "_", label_raw)

pkg_ver <- function(p) {
  if (!requireNamespace(p, quietly = TRUE)) return(NA_character_)
  as.character(utils::packageVersion(p))
}

env_vals <- c(
  label, "curl-probe",
  flat(cv$version), flat(cv$ssl_version), flat(cv$ssl_backend),
  flat(cv$protocols), flat(cv$libidn), flat(cv$libssh), flat(cv$libz),
  R.version.string, R.version$platform,
  flat(si[["sysname"]]), flat(si[["release"]]), flat(si[["version"]]),
  flat(si[["machine"]]),
  Sys.getlocale(), flat(getOption("encoding")),
  pkg_ver("curl"),
  format(Sys.time(), "%Y-%m-%dT%H:%M:%S", tz = "UTC")
)
env_df <- data.frame(key = env_keys, value = json_escape(env_vals),
                     stringsAsFactors = FALSE)

# ---- write -----------------------------------------------------------------

out_dir <- Sys.getenv("RURL_DETERMINISM_OUT", "")
if (!nzchar(out_dir)) out_dir <- file.path(dirname(corpus_path), "out")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

write_ascii_csv <- function(df, path) {
  bad <- vapply(df, function(col) any(grepl("[^\x20-\x7e]", col)), logical(1))
  if (any(bad)) {
    stop("refusing to write non-ASCII column(s): ",
         toString(names(df)[bad]), " -> ", path)
  }
  con <- file(path, open = "wb")        # binary: force LF, never CRLF
  on.exit(close(con))
  utils::write.csv(df, con, row.names = FALSE, quote = TRUE, eol = "\n")
  invisible(path)
}

dump_path <- file.path(out_dir, paste0("curl-", label, ".csv"))
env_path <- file.path(out_dir, paste0("curlenv-", label, ".csv"))
write_ascii_csv(dump, dump_path)
write_ascii_csv(env_df, env_path)

cat(sprintf("wrote %s (%d rows)\nwrote %s (%d keys)\n",
            dump_path, nrow(dump), env_path, nrow(env_df)))
