#!/usr/bin/env Rscript
# Cross-platform parse-determinism dump (RURL-ttrcfneq).
#
# NOT a test and NOT shipped in the package (.Rbuildignore'd). Runs the probe
# corpus through safe_parse_urls() under all three url_standard settings and
# records EVERY output column, so the same script run on another libcurl /
# platform produces a directly diff-able artifact. rurl parses via
# curl::curl_parse_url(); libcurl's edge-case behavior varies by version and
# build, so rurl's output is (today) non-deterministic across machines. This
# dump is the evidence; later it becomes the permanent regression harness that
# proves determinism was achieved.
#
#   Rscript tools/determinism/parse-dump.R
#   Rscript -e 'devtools::load_all(); source("tools/determinism/parse-dump.R")'
#
# Inputs:  tools/determinism/corpus.csv (generated by corpus.R)
# Outputs: tools/determinism/out/dump-<LABEL>.csv
#          tools/determinism/out/env-<LABEL>.csv
# LABEL comes from $RURL_DETERMINISM_LABEL, else <sysname>-libcurl<version>.
#
# $RURL_DETERMINISM_RUN optionally marks this as a repeat run. It does two
# things:
#   * it TAGS the output, writing <RUN>-dump-<LABEL>.csv /
#     <RUN>-env-<LABEL>.csv instead. Unset (the default) writes the untagged
#     names, so the primary run is unchanged. The tag PREFIXES rather than
#     suffixes: the gate enumerates cells with a `^dump-` glob, so a suffixed
#     repeat dump would register as an extra, unexpected cell.
#   * it PERTURBS the corpus order under a fixed, recorded seed
#     (CORPUS_SHUFFLE_SEED, written to env-<LABEL>.csv as `corpus_order` +
#     `corpus_shuffle_seed`). An identical second run proves only
#     process/temporal invariance; shuffling varies something that MUST NOT
#     matter, so the repeat also probes order-dependence and session-cache
#     state leakage. Row order in the dump therefore DIFFERS between run 1 and
#     run 2 by design -- compare-gate.R's projection is sorted on
#     (id, url_standard), so it compares content, not file order.
#
# ZERO package dependencies beyond base R + an installed rurl (curl comes with
# rurl). stringi is PROBED, never required. No jsonlite, no devtools.
#
# ENCODING CONTRACT. Every value column -- inputs and outputs alike -- is a
# JSON string literal: quoted, ASCII-only, non-ASCII as \uXXXX. The bare token
# `null` (unquoted) means R NA, which is therefore distinguishable from the
# string "NA" (written "NA") and from "" (written ""). Files are LF-terminated
# and pure ASCII by construction: C0 controls, CR/LF, astral and non-character
# code points cannot survive a raw CSV cell.
#
# The rendering is derived from the value's BYTES, never from the session
# locale -- see utf8_codepoints() below. A byte that is not part of
# well-formed UTF-8 is written as \udcXX, and the per-value Encoding() mark is
# recorded in the `encoding_marks` column, so a charset difference is DATA
# rather than a silent difference in how the dump renders.
# ----------------------------------------------------------------------------

# ---- rurl loading (matches inst/bench/standard-parity.R) -------------------

if (!requireNamespace("rurl", quietly = TRUE) &&
      !exists("safe_parse_urls", mode = "function")) {
  stop("rurl not available: install it or run after devtools::load_all().")
}
spu <- if (exists("safe_parse_urls", mode = "function")) {
  get("safe_parse_urls")
} else {
  rurl::safe_parse_urls
}

# ---- JSON escape (base R) --------------------------------------------------
# Deliberately duplicated from corpus.R so this script is copy-one-file
# runnable inside a container. The self-test below round-trips every corpus row
# through THIS copy, which also proves the two copies agree.

# LOCALE-INVARIANT code points (RURL-cupshtnh). enc2utf8() must NEVER appear
# here: it TRANSCODES from the session locale, so the SAME bytes rendered
# under LC_ALL=C and under en_US.UTF-8 produced different text and the
# harness ended up measuring itself instead of rurl (it turned an unmarked
# UTF-8 host into "<d0><b0>pple.com" under C, and threw on a
# marked-but-invalid-UTF-8 value). This reads the BYTES and the declared
# Encoding() mark only:
#
#   * bytes that form well-formed UTF-8 decode to their code points --
#     whatever the session locale, and whatever mark the string carries;
#   * every other byte becomes the lone low surrogate 0xDC00 + byte (the
#     PEP-383 "surrogateescape" convention): deterministic, byte-reversible,
#     written as ASCII \udcXX, and unreachable by decoding valid UTF-8, so it
#     can never be confused with a genuine code point.
#
# The escaper is therefore TOTAL: invalid UTF-8 is RENDERED, never an error.
# The corpus deliberately produces such values, and a dump that abandons a
# row is worse evidence than one that records the bytes it saw.

utf8_codepoints <- function(s) {
  s8 <- s
  Encoding(s8) <- "UTF-8"                # declare; never transcode
  cps <- tryCatch(suppressWarnings(utf8ToInt(s8)),
                  error = function(e) NA_integer_)
  if (!anyNA(cps)) return(cps)
  raw_codepoints(charToRaw(s))
}

# Strict UTF-8 decode of a raw vector. Truncated sequences, bad continuation
# bytes, overlong forms, surrogates and anything above U+10FFFF are rejected
# one byte at a time into the surrogateescape range.
raw_codepoints <- function(b) {
  n <- length(b)
  if (n == 0L) return(integer(0))
  v <- as.integer(b)
  cps <- integer(n)
  k <- 0L
  i <- 1L
  while (i <= n) {
    b0 <- v[i]
    len <- if (b0 <= 0x7fL) {
      1L
    } else if (b0 >= 0xc2L && b0 <= 0xdfL) {
      2L
    } else if (b0 >= 0xe0L && b0 <= 0xefL) {
      3L
    } else if (b0 >= 0xf0L && b0 <= 0xf4L) {
      4L
    } else {
      0L
    }
    cp <- NA_integer_
    if (len > 0L && i + len - 1L <= n) {
      acc <- bitwAnd(b0, c(0x7fL, 0x1fL, 0x0fL, 0x07L)[len])
      ok <- TRUE
      for (j in seq_len(len - 1L)) {
        cont <- v[i + j]
        if (cont < 0x80L || cont > 0xbfL) {
          ok <- FALSE
          break
        }
        acc <- acc * 64L + (cont - 0x80L)
      }
      lo <- c(0L, 0x80L, 0x800L, 0x10000L)[len]
      if (ok && acc >= lo && acc <= 0x10ffffL &&
            (acc < 0xd800L || acc > 0xdfffL)) {
        cp <- acc
      }
    }
    k <- k + 1L
    if (is.na(cp)) {
      cps[k] <- 0xdc00L + b0
      i <- i + 1L
    } else {
      cps[k] <- cp
      i <- i + len
    }
  }
  cps[seq_len(k)]
}

json_escape_one <- function(s) {
  if (is.na(s)) return("null")
  cps <- utf8_codepoints(s)
  if (length(cps) == 0L) return("\"\"")
  out <- character(length(cps))
  for (i in seq_along(cps)) {
    cp <- cps[i]
    out[i] <- if (cp == 34L) {
      "\\\""
    } else if (cp == 92L) {
      "\\\\"
    } else if (cp == 8L) {
      "\\b"
    } else if (cp == 9L) {
      "\\t"
    } else if (cp == 10L) {
      "\\n"
    } else if (cp == 12L) {
      "\\f"
    } else if (cp == 13L) {
      "\\r"
    } else if (cp >= 32L && cp <= 126L) {
      intToUtf8(cp)
    } else if (cp <= 0xFFFFL) {
      sprintf("\\u%04x", cp)
    } else {
      u <- cp - 0x10000L
      sprintf("\\u%04x\\u%04x",
              0xD800L + u %/% 0x400L, 0xDC00L + u %% 0x400L)
    }
  }
  paste0("\"", paste(out, collapse = ""), "\"")
}

json_escape <- function(x) {
  vapply(x, json_escape_one, character(1), USE.NAMES = FALSE)
}

json_unescape_one <- function(s) {
  if (is.na(s) || identical(s, "null")) return(NA_character_)
  n <- nchar(s)
  if (n < 2L || substr(s, 1L, 1L) != "\"" || substr(s, n, n) != "\"") {
    stop("not a JSON string literal: ", s)
  }
  ch <- strsplit(substr(s, 2L, n - 1L), "", fixed = TRUE)[[1]]
  cps <- integer(0)
  i <- 1L
  m <- length(ch)
  while (i <= m) {
    if (ch[i] != "\\") {
      cps <- c(cps, utf8ToInt(ch[i]))
      i <- i + 1L
      next
    }
    e <- ch[i + 1L]
    if (e == "u") {
      hi <- strtoi(paste(ch[(i + 2L):(i + 5L)], collapse = ""), 16L)
      i <- i + 6L
      if (hi >= 0xD800L && hi <= 0xDBFFL && i + 5L <= m &&
            identical(ch[i], "\\") && identical(ch[i + 1L], "u")) {
        lo <- strtoi(paste(ch[(i + 2L):(i + 5L)], collapse = ""), 16L)
        i <- i + 6L
        hi <- 0x10000L + (hi - 0xD800L) * 0x400L + (lo - 0xDC00L)
      }
      cps <- c(cps, hi)
    } else {
      simple <- c("\"" = 34L, "\\" = 92L, "/" = 47L, "b" = 8L,
                  "f" = 12L, "n" = 10L, "r" = 13L, "t" = 9L)[e]
      if (is.na(simple)) stop("bad JSON escape: \\", e)
      cps <- c(cps, unname(simple))
      i <- i + 2L
    }
  }
  if (length(cps) == 0L) return("")
  intToUtf8(cps)
}

json_unescape <- function(x) {
  vapply(x, json_unescape_one, character(1), USE.NAMES = FALSE)
}

# ---- locate the corpus -----------------------------------------------------

find_file <- function(rel) {
  cand <- c(rel, file.path("tools", "determinism", basename(rel)),
            basename(rel))
  hit <- cand[file.exists(cand)][1]
  if (is.na(hit)) stop("cannot locate ", rel, " (run from the repo root).")
  hit
}

corpus_path <- find_file(file.path("tools", "determinism", "corpus.csv"))
corpus <- utils::read.csv(corpus_path, colClasses = "character",
                          fileEncoding = "UTF-8", stringsAsFactors = FALSE)

# ---- repeat-run perturbation: seeded corpus shuffle (RURL-ptsijueb) --------
#
# $RURL_DETERMINISM_RUN is read HERE, above the parse, and not merely at the
# write step: a repeat run does more than redirect its output path, it PERTURBS
# THE CORPUS ORDER. An identically-configured second run can only prove
# process/temporal invariance; varying something that MUST NOT matter is what
# turns the repeat into a probe of order-dependence and cross-row cache /
# state leakage (rurl's cache environments live for the whole session, so a
# leak between rows is a real failure mode). compare-gate.R diffs a projection
# keyed and sorted on (id, url_standard), so a correct parser is
# order-insensitive by construction: the shuffled run must reproduce run 1
# byte-for-byte after projection, and any difference is a finding.
run_tag <- gsub("[^A-Za-z0-9._-]", "_", Sys.getenv("RURL_DETERMINISM_RUN", ""))
tag <- if (nzchar(run_tag)) paste0(run_tag, "-") else ""

# FIXED and RECORDED, never ambient (no env override on purpose): the seed is
# written to env-<LABEL>.csv below, and a permutation whose seed cannot be
# recovered from the artifact is not reproducible evidence. Nothing depends on
# this constant's VALUE -- order-insensitivity must hold for every permutation
# -- so it is a replay handle, not a tuning knob.
CORPUS_SHUFFLE_SEED <- 20260725L

# WHY NOT set.seed() + sample(): R's RNG is not a stable cross-version
# contract. R 3.6.0 changed the DEFAULT sample.kind ("Rounding" ->
# "Rejection") and silently changed every sample() result; pinning
# kind=/sample.kind= would both depend on arguments that did not exist before
# R 3.6.0 and bet on R never re-tuning a generator again. This matrix spans
# oldrel / release / devel deliberately, so "same seed => same permutation"
# has to hold across R versions BY CONSTRUCTION, not by convention. The
# permutation is therefore computed in full, here, from an explicit 32-bit
# linear congruential generator (Numerical Recipes constants) driving a
# Fisher-Yates shuffle: exact in double arithmetic (1664525 * (2^32 - 1) +
# 1013904223 < 2^53), a function of (seed, n) alone, and it never touches
# .Random.seed -- so it also cannot perturb the RNG state the parse itself
# runs under, which would confound the very thing being measured. Modulo bias
# is irrelevant: this needs a reproducible permutation, not a uniform one.
seeded_permutation <- function(n, seed) {
  if (n < 2L) {
    return(seq_len(n))
  }
  state <- seed %% 4294967296
  idx <- seq_len(n)
  for (i in n:2L) {
    state <- (1664525 * state + 1013904223) %% 4294967296
    j <- 1L + as.integer(state %% i)
    keep <- idx[i]
    idx[i] <- idx[j]
    idx[j] <- keep
  }
  idx
}

corpus_order <- "as-read"
if (nzchar(run_tag)) {
  corpus_order <- "shuffled"
  corpus <- corpus[seeded_permutation(nrow(corpus), CORPUS_SHUFFLE_SEED), ,
                   drop = FALSE]
  rownames(corpus) <- NULL
  cat(sprintf("repeat run '%s': corpus shuffled, seed=%d, rows=%d\n",
              run_tag, CORPUS_SHUFFLE_SEED, nrow(corpus)))
}

inputs <- json_unescape(corpus$input_json)

# ---- round-trip self-test (must run BEFORE any parsing) --------------------
# A silently lossy transport would poison every downstream diff, so fail loud.

selftest <- function() {
  probes <- c(
    inputs,
    "a\r\nb",                       # literal CRLF
    intToUtf8(c(0x01, 0x1F, 0x7F)), # NUL-free C0 controls + DEL
    intToUtf8(0x1F600),             # astral plane
    intToUtf8(0xFFFF),              # non-character
    "", " ", "NA", "null", "\"quoted\"", "back\\slash", "sl/ash"
  )
  esc <- json_escape(probes)
  if (any(grepl("[^\x20-\x7e]", esc))) {
    stop("self-test FAILED: escaped output is not ASCII-only")
  }
  back <- json_unescape(esc)
  if (!identical(back, probes)) {
    bad <- which(back != probes)
    stop("self-test FAILED: JSON round-trip lossy at ", length(bad),
         " probe(s), first index ", bad[1])
  }
  if (!is.na(json_unescape_one("null")) ||
        !identical(json_unescape_one("\"NA\""), "NA") ||
        !identical(json_unescape_one("\"\""), "")) {
    stop("self-test FAILED: NA / \"NA\" / \"\" are not distinguishable")
  }
  invisible(TRUE)
}
selftest()
cat("self-test: JSON round-trip OK over", length(inputs), "corpus rows\n")

# ---- parse -----------------------------------------------------------------

OUT_COLS <- c(
  "original_url", "scheme", "host", "port", "path", "query", "fragment",
  "user", "password", "domain", "tld", "domain_ascii", "domain_unicode",
  "tld_ascii", "tld_unicode", "is_ip_host", "clean_url", "parse_status"
)

na_frame <- function(n) {
  d <- as.data.frame(
    matrix(NA_character_, nrow = n, ncol = length(OUT_COLS)),
    stringsAsFactors = FALSE
  )
  names(d) <- OUT_COLS
  d
}

# Capture conditions as DATA. A container that dies mid-corpus yields no
# evidence, so nothing here is allowed to abort the run.
capture_call <- function(x, std) {
  acc <- new.env(parent = emptyenv())
  acc$msgs <- character(0)
  note <- function(prefix, cnd) {
    acc$msgs <- c(acc$msgs, paste0(prefix, conditionMessage(cnd)))
  }
  res <- withCallingHandlers(
    tryCatch(
      if (is.null(std)) spu(x) else spu(x, url_standard = std),
      error = function(e) {
        note("error: ", e)
        NULL
      }
    ),
    warning = function(w) {
      note("warning: ", w)
      invokeRestart("muffleWarning")
    }
  )
  list(res = res, cond = paste(acc$msgs, collapse = " | "))
}

# Fast path: one vectorized call per url_standard. If it errors OR warns, redo
# per row so each condition is attributed to the row that produced it (a
# vectorized warning cannot be pinned to an element).
run_standard <- function(std) {
  n <- length(inputs)
  cond <- rep("", n)
  hit <- capture_call(inputs, std)
  ok <- !is.null(hit$res) && nrow(hit$res) == n
  if (ok && !nzchar(hit$cond)) {
    return(list(res = hit$res[, OUT_COLS, drop = FALSE], cond = cond))
  }
  res <- na_frame(n)
  for (i in seq_len(n)) {
    one <- capture_call(inputs[i], std)
    cond[i] <- one$cond
    if (!is.null(one$res) && nrow(one$res) == 1L) {
      res[i, ] <- lapply(OUT_COLS, function(k) as.character(one$res[[k]][1]))
    }
  }
  list(res = res, cond = cond)
}

# ---- encoding marks, as DATA -----------------------------------------------
# The charset axis used to be captured ONLY as the free-text `locale` /
# `encoding` env keys, never per value -- so a lost or changed Encoding() mark
# was invisible in the dump except through the escaper mangling it caused,
# which is precisely the confound this harness exists to avoid.
# `encoding_marks` records the mark of every output value: one character per
# column, in OUT_COLS order.
#
#   8 = "UTF-8"   l = "latin1"   b = "bytes"   u = "unknown" (native)
#   . = NA        ? = anything else a future R might return
#
# R does not mark a pure-ASCII string, so `u` is expected for ASCII values and
# says nothing on its own; what matters is that the same input yields the same
# mark string on every platform, locale and R version.

MARK_CODES <- c(`UTF-8` = "8", latin1 = "l", bytes = "b", unknown = "u")

mark_code <- function(x) {
  x <- as.character(x)
  code <- unname(MARK_CODES[Encoding(x)])
  code[is.na(code)] <- "?"
  code[is.na(x)] <- "."
  code
}

standards <- list(default = NULL, rfc3986 = "rfc3986", whatwg = "whatwg")
parts <- list()
for (nm in names(standards)) {
  t0 <- Sys.time()
  r <- run_standard(standards[[nm]])
  parts[[nm]] <- data.frame(
    id = corpus$id,
    construct = corpus$construct,
    input_json = corpus$input_json,
    url_standard = nm,
    r_condition = json_escape(r$cond),
    stringsAsFactors = FALSE
  )
  for (k in OUT_COLS) {
    parts[[nm]][[k]] <- json_escape(as.character(r$res[[k]]))
  }
  parts[[nm]][["encoding_marks"]] <- json_escape(
    do.call(paste0, lapply(OUT_COLS, function(k) mark_code(r$res[[k]])))
  )
  cat(sprintf("url_standard=%-8s rows=%d conditions=%d (%.1fs)\n",
              nm, nrow(parts[[nm]]), sum(nzchar(r$cond)),
              as.numeric(difftime(Sys.time(), t0, units = "secs"))))
}
dump <- do.call(rbind, parts)
rownames(dump) <- NULL

# ---- environment fingerprint -----------------------------------------------

pkg_ver <- function(p) {
  if (!requireNamespace(p, quietly = TRUE)) return(NA_character_)
  as.character(utils::packageVersion(p))
}
cv <- tryCatch(curl::curl_version(), error = function(e) list())
si <- Sys.info()
flat <- function(x) {
  if (length(x) == 0L || all(is.na(x))) return(NA_character_)
  paste(as.character(x), collapse = ";")
}

env_keys <- c(
  "label", "libcurl_version", "libcurl_ssl_version", "libcurl_ssl_backend",
  "libcurl_protocols", "libcurl_libidn", "libcurl_libssh",
  "r_version", "r_platform", "sysname", "release", "machine",
  "locale", "encoding", "icu_version", "unicode_version",
  "rurl_version", "curl_version_pkg", "pslr_version", "punycoder_version",
  "stringi_version", "run_utc",
  # Repeat-run perturbation (RURL-ptsijueb). `corpus_order` is "as-read" for
  # the primary run and "shuffled" for a tagged repeat run;
  # `corpus_shuffle_seed` is the seed that generated the permutation, or the
  # `null` sentinel when no shuffle was applied. Recorded so a nondeterminism
  # finding is replayable from the artifact alone, without re-deriving which
  # order produced it. ADDITIVE: the key set is a tidy key/value list and
  # nothing validates it as a closed set (compare-gate.R's read_meta_kv reads
  # locale-<LABEL>.csv, not this file), so appending cannot orphan a consumer.
  "corpus_order", "corpus_shuffle_seed"
)

label_raw <- Sys.getenv("RURL_DETERMINISM_LABEL", "")
if (!nzchar(label_raw)) {
  label_raw <- paste0(flat(si[["sysname"]]), "-libcurl", flat(cv$version))
}
label <- gsub("[^A-Za-z0-9._-]", "_", label_raw)

sti <- if (requireNamespace("stringi", quietly = TRUE)) {
  tryCatch(stringi::stri_info(), error = function(e) list())
} else {
  list()
}

env_vals <- c(
  label,
  flat(cv$version), flat(cv$ssl_version), flat(cv$ssl_backend),
  flat(cv$protocols), flat(cv$libidn), flat(cv$libssh),
  R.version.string, R.version$platform,
  flat(si[["sysname"]]), flat(si[["release"]]), flat(si[["machine"]]),
  Sys.getlocale(), flat(getOption("encoding")),
  flat(sti$ICU.version), flat(sti$Unicode.version),
  pkg_ver("rurl"), pkg_ver("curl"), pkg_ver("pslr"), pkg_ver("punycoder"),
  pkg_ver("stringi"),
  format(Sys.time(), "%Y-%m-%dT%H:%M:%S", tz = "UTC"),
  corpus_order,
  if (identical(corpus_order, "shuffled")) {
    as.character(CORPUS_SHUFFLE_SEED)
  } else {
    NA_character_
  }
)
env_df <- data.frame(key = env_keys, value = json_escape(env_vals),
                     stringsAsFactors = FALSE)

# ---- write -----------------------------------------------------------------

out_dir <- file.path(dirname(corpus_path), "out")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

write_ascii_csv <- function(df, path) {
  bad <- vapply(df, function(col) any(grepl("[^\x20-\x7e]", col)), logical(1))
  if (any(bad)) {
    stop("refusing to write non-ASCII column(s): ",
         toString(names(df)[bad]), " -> ", path)
  }
  con <- file(path, open = "wb")        # binary: force LF, never CRLF
  on.exit(close(con))
  utils::write.csv(df, con, row.names = FALSE, quote = TRUE, eol = "\n")
  invisible(path)
}

# Repeat-run tag (G4.2 / P5.2 "two pinned runs of the same comparable cell").
# `run_tag` / `tag` are computed WITH the corpus shuffle far above, because the
# tag decides the input order as well as the output path. Sanitized like the
# label, and PREFIXED -- see the header: the gate's cell glob is anchored
# `^dump-`, so a suffixed repeat dump would look like its own cell.
dump_path <- file.path(out_dir, paste0(tag, "dump-", label, ".csv"))
env_path <- file.path(out_dir, paste0(tag, "env-", label, ".csv"))
write_ascii_csv(dump, dump_path)
write_ascii_csv(env_df, env_path)

cat(sprintf("wrote %s (%d rows)\nwrote %s (%d keys)\n",
            dump_path, nrow(dump), env_path, nrow(env_df)))
