#!/usr/bin/env Rscript
# Cross-platform parse-determinism dump (RURL-ttrcfneq).
#
# NOT a test and NOT shipped in the package (.Rbuildignore'd). Runs the probe
# corpus through safe_parse_urls() under all three url_standard settings and
# records EVERY output column, so the same script run on another libcurl /
# platform produces a directly diff-able artifact. rurl parses via
# curl::curl_parse_url(); libcurl's edge-case behavior varies by version and
# build, so rurl's output is (today) non-deterministic across machines. This
# dump is the evidence; later it becomes the permanent regression harness that
# proves determinism was achieved.
#
#   Rscript tools/determinism/parse-dump.R
#   Rscript -e 'devtools::load_all(); source("tools/determinism/parse-dump.R")'
#
# Inputs:  tools/determinism/corpus.csv (generated by corpus.R)
# Outputs: tools/determinism/out/dump-<LABEL>.csv
#          tools/determinism/out/env-<LABEL>.csv
# LABEL comes from $RURL_DETERMINISM_LABEL, else <sysname>-libcurl<version>.
#
# ZERO package dependencies beyond base R + an installed rurl (curl comes with
# rurl). stringi is PROBED, never required. No jsonlite, no devtools.
#
# ENCODING CONTRACT. Every value column -- inputs and outputs alike -- is a
# JSON string literal: quoted, ASCII-only, non-ASCII as \uXXXX. The bare token
# `null` (unquoted) means R NA, which is therefore distinguishable from the
# string "NA" (written "NA") and from "" (written ""). Files are LF-terminated
# and pure ASCII by construction: C0 controls, CR/LF, astral and non-character
# code points cannot survive a raw CSV cell.
# ----------------------------------------------------------------------------

# ---- rurl loading (matches inst/bench/standard-parity.R) -------------------

if (!requireNamespace("rurl", quietly = TRUE) &&
      !exists("safe_parse_urls", mode = "function")) {
  stop("rurl not available: install it or run after devtools::load_all().")
}
spu <- if (exists("safe_parse_urls", mode = "function")) {
  get("safe_parse_urls")
} else {
  rurl::safe_parse_urls
}

# ---- JSON escape (base R) --------------------------------------------------
# Deliberately duplicated from corpus.R so this script is copy-one-file
# runnable inside a container. The self-test below round-trips every corpus row
# through THIS copy, which also proves the two copies agree.

json_escape_one <- function(s) {
  if (is.na(s)) return("null")
  cps <- utf8ToInt(enc2utf8(s))
  if (length(cps) == 1L && is.na(cps)) {
    stop("value is not valid UTF-8; cannot escape")
  }
  if (length(cps) == 0L) return("\"\"")
  out <- character(length(cps))
  for (i in seq_along(cps)) {
    cp <- cps[i]
    out[i] <- if (cp == 34L) {
      "\\\""
    } else if (cp == 92L) {
      "\\\\"
    } else if (cp == 8L) {
      "\\b"
    } else if (cp == 9L) {
      "\\t"
    } else if (cp == 10L) {
      "\\n"
    } else if (cp == 12L) {
      "\\f"
    } else if (cp == 13L) {
      "\\r"
    } else if (cp >= 32L && cp <= 126L) {
      intToUtf8(cp)
    } else if (cp <= 0xFFFFL) {
      sprintf("\\u%04x", cp)
    } else {
      u <- cp - 0x10000L
      sprintf("\\u%04x\\u%04x",
              0xD800L + u %/% 0x400L, 0xDC00L + u %% 0x400L)
    }
  }
  paste0("\"", paste(out, collapse = ""), "\"")
}

json_escape <- function(x) {
  vapply(x, json_escape_one, character(1), USE.NAMES = FALSE)
}

json_unescape_one <- function(s) {
  if (is.na(s) || identical(s, "null")) return(NA_character_)
  n <- nchar(s)
  if (n < 2L || substr(s, 1L, 1L) != "\"" || substr(s, n, n) != "\"") {
    stop("not a JSON string literal: ", s)
  }
  ch <- strsplit(substr(s, 2L, n - 1L), "", fixed = TRUE)[[1]]
  cps <- integer(0)
  i <- 1L
  m <- length(ch)
  while (i <= m) {
    if (ch[i] != "\\") {
      cps <- c(cps, utf8ToInt(ch[i]))
      i <- i + 1L
      next
    }
    e <- ch[i + 1L]
    if (e == "u") {
      hi <- strtoi(paste(ch[(i + 2L):(i + 5L)], collapse = ""), 16L)
      i <- i + 6L
      if (hi >= 0xD800L && hi <= 0xDBFFL && i + 5L <= m &&
            identical(ch[i], "\\") && identical(ch[i + 1L], "u")) {
        lo <- strtoi(paste(ch[(i + 2L):(i + 5L)], collapse = ""), 16L)
        i <- i + 6L
        hi <- 0x10000L + (hi - 0xD800L) * 0x400L + (lo - 0xDC00L)
      }
      cps <- c(cps, hi)
    } else {
      simple <- c("\"" = 34L, "\\" = 92L, "/" = 47L, "b" = 8L,
                  "f" = 12L, "n" = 10L, "r" = 13L, "t" = 9L)[e]
      if (is.na(simple)) stop("bad JSON escape: \\", e)
      cps <- c(cps, unname(simple))
      i <- i + 2L
    }
  }
  if (length(cps) == 0L) return("")
  intToUtf8(cps)
}

json_unescape <- function(x) {
  vapply(x, json_unescape_one, character(1), USE.NAMES = FALSE)
}

# ---- locate the corpus -----------------------------------------------------

find_file <- function(rel) {
  cand <- c(rel, file.path("tools", "determinism", basename(rel)),
            basename(rel))
  hit <- cand[file.exists(cand)][1]
  if (is.na(hit)) stop("cannot locate ", rel, " (run from the repo root).")
  hit
}

corpus_path <- find_file(file.path("tools", "determinism", "corpus.csv"))
corpus <- utils::read.csv(corpus_path, colClasses = "character",
                          fileEncoding = "UTF-8", stringsAsFactors = FALSE)
inputs <- json_unescape(corpus$input_json)

# ---- round-trip self-test (must run BEFORE any parsing) --------------------
# A silently lossy transport would poison every downstream diff, so fail loud.

selftest <- function() {
  probes <- c(
    inputs,
    "a\r\nb",                       # literal CRLF
    intToUtf8(c(0x01, 0x1F, 0x7F)), # NUL-free C0 controls + DEL
    intToUtf8(0x1F600),             # astral plane
    intToUtf8(0xFFFF),              # non-character
    "", " ", "NA", "null", "\"quoted\"", "back\\slash", "sl/ash"
  )
  esc <- json_escape(probes)
  if (any(grepl("[^\x20-\x7e]", esc))) {
    stop("self-test FAILED: escaped output is not ASCII-only")
  }
  back <- json_unescape(esc)
  if (!identical(back, probes)) {
    bad <- which(back != probes)
    stop("self-test FAILED: JSON round-trip lossy at ", length(bad),
         " probe(s), first index ", bad[1])
  }
  if (!is.na(json_unescape_one("null")) ||
        !identical(json_unescape_one("\"NA\""), "NA") ||
        !identical(json_unescape_one("\"\""), "")) {
    stop("self-test FAILED: NA / \"NA\" / \"\" are not distinguishable")
  }
  invisible(TRUE)
}
selftest()
cat("self-test: JSON round-trip OK over", length(inputs), "corpus rows\n")

# ---- parse -----------------------------------------------------------------

OUT_COLS <- c(
  "original_url", "scheme", "host", "port", "path", "query", "fragment",
  "user", "password", "domain", "tld", "domain_ascii", "domain_unicode",
  "tld_ascii", "tld_unicode", "is_ip_host", "clean_url", "parse_status"
)

na_frame <- function(n) {
  d <- as.data.frame(
    matrix(NA_character_, nrow = n, ncol = length(OUT_COLS)),
    stringsAsFactors = FALSE
  )
  names(d) <- OUT_COLS
  d
}

# Capture conditions as DATA. A container that dies mid-corpus yields no
# evidence, so nothing here is allowed to abort the run.
capture_call <- function(x, std) {
  acc <- new.env(parent = emptyenv())
  acc$msgs <- character(0)
  note <- function(prefix, cnd) {
    acc$msgs <- c(acc$msgs, paste0(prefix, conditionMessage(cnd)))
  }
  res <- withCallingHandlers(
    tryCatch(
      if (is.null(std)) spu(x) else spu(x, url_standard = std),
      error = function(e) {
        note("error: ", e)
        NULL
      }
    ),
    warning = function(w) {
      note("warning: ", w)
      invokeRestart("muffleWarning")
    }
  )
  list(res = res, cond = paste(acc$msgs, collapse = " | "))
}

# Fast path: one vectorized call per url_standard. If it errors OR warns, redo
# per row so each condition is attributed to the row that produced it (a
# vectorized warning cannot be pinned to an element).
run_standard <- function(std) {
  n <- length(inputs)
  cond <- rep("", n)
  hit <- capture_call(inputs, std)
  ok <- !is.null(hit$res) && nrow(hit$res) == n
  if (ok && !nzchar(hit$cond)) {
    return(list(res = hit$res[, OUT_COLS, drop = FALSE], cond = cond))
  }
  res <- na_frame(n)
  for (i in seq_len(n)) {
    one <- capture_call(inputs[i], std)
    cond[i] <- one$cond
    if (!is.null(one$res) && nrow(one$res) == 1L) {
      res[i, ] <- lapply(OUT_COLS, function(k) as.character(one$res[[k]][1]))
    }
  }
  list(res = res, cond = cond)
}

standards <- list(default = NULL, rfc3986 = "rfc3986", whatwg = "whatwg")
parts <- list()
for (nm in names(standards)) {
  t0 <- Sys.time()
  r <- run_standard(standards[[nm]])
  parts[[nm]] <- data.frame(
    id = corpus$id,
    construct = corpus$construct,
    input_json = corpus$input_json,
    url_standard = nm,
    r_condition = json_escape(r$cond),
    stringsAsFactors = FALSE
  )
  for (k in OUT_COLS) {
    parts[[nm]][[k]] <- json_escape(as.character(r$res[[k]]))
  }
  cat(sprintf("url_standard=%-8s rows=%d conditions=%d (%.1fs)\n",
              nm, nrow(parts[[nm]]), sum(nzchar(r$cond)),
              as.numeric(difftime(Sys.time(), t0, units = "secs"))))
}
dump <- do.call(rbind, parts)
rownames(dump) <- NULL

# ---- environment fingerprint -----------------------------------------------

pkg_ver <- function(p) {
  if (!requireNamespace(p, quietly = TRUE)) return(NA_character_)
  as.character(utils::packageVersion(p))
}
cv <- tryCatch(curl::curl_version(), error = function(e) list())
si <- Sys.info()
flat <- function(x) {
  if (length(x) == 0L || all(is.na(x))) return(NA_character_)
  paste(as.character(x), collapse = ";")
}

env_keys <- c(
  "label", "libcurl_version", "libcurl_ssl_version", "libcurl_ssl_backend",
  "libcurl_protocols", "libcurl_libidn", "libcurl_libssh",
  "r_version", "r_platform", "sysname", "release", "machine",
  "locale", "encoding", "icu_version", "unicode_version",
  "rurl_version", "curl_version_pkg", "pslr_version", "punycoder_version",
  "stringi_version", "run_utc"
)

label_raw <- Sys.getenv("RURL_DETERMINISM_LABEL", "")
if (!nzchar(label_raw)) {
  label_raw <- paste0(flat(si[["sysname"]]), "-libcurl", flat(cv$version))
}
label <- gsub("[^A-Za-z0-9._-]", "_", label_raw)

sti <- if (requireNamespace("stringi", quietly = TRUE)) {
  tryCatch(stringi::stri_info(), error = function(e) list())
} else {
  list()
}

env_vals <- c(
  label,
  flat(cv$version), flat(cv$ssl_version), flat(cv$ssl_backend),
  flat(cv$protocols), flat(cv$libidn), flat(cv$libssh),
  R.version.string, R.version$platform,
  flat(si[["sysname"]]), flat(si[["release"]]), flat(si[["machine"]]),
  Sys.getlocale(), flat(getOption("encoding")),
  flat(sti$ICU.version), flat(sti$Unicode.version),
  pkg_ver("rurl"), pkg_ver("curl"), pkg_ver("pslr"), pkg_ver("punycoder"),
  pkg_ver("stringi"),
  format(Sys.time(), "%Y-%m-%dT%H:%M:%S", tz = "UTC")
)
env_df <- data.frame(key = env_keys, value = json_escape(env_vals),
                     stringsAsFactors = FALSE)

# ---- write -----------------------------------------------------------------

out_dir <- file.path(dirname(corpus_path), "out")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

write_ascii_csv <- function(df, path) {
  bad <- vapply(df, function(col) any(grepl("[^\x20-\x7e]", col)), logical(1))
  if (any(bad)) {
    stop("refusing to write non-ASCII column(s): ",
         toString(names(df)[bad]), " -> ", path)
  }
  con <- file(path, open = "wb")        # binary: force LF, never CRLF
  on.exit(close(con))
  utils::write.csv(df, con, row.names = FALSE, quote = TRUE, eol = "\n")
  invisible(path)
}

dump_path <- file.path(out_dir, paste0("dump-", label, ".csv"))
env_path <- file.path(out_dir, paste0("env-", label, ".csv"))
write_ascii_csv(dump, dump_path)
write_ascii_csv(env_df, env_path)

cat(sprintf("wrote %s (%d rows)\nwrote %s (%d keys)\n",
            dump_path, nrow(dump), env_path, nrow(env_df)))
